account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
  path('',views.index, name='index'),
  path('search-results/', views.search_result, name='search-result'),
  path('about/', views.about, name='about'),
  path('signup/', views.signup, name='signup'),
  path('login/', views.loginuser, name='login'),
  path('take_a_tour/', views.take_a_tour, name='take-a-tour'),
  path('logout/', views.logoutuser, name='logout'),

  path('profile/<str:pk>/', views.profile, name='profile'),
  path('profile_form/<str:pk>/', views.edit_profile, name='profile_form'),

  # path('search_profiles/<str:search_query>/', views.search_profiles, name='search_profiles'),
  path('search_profiles/', views.search_profiles, name='search_profiles'),

  path('send_friend_request/<str:sender_id>/<str:receiver_id>/', views.send_frnd_req, name='send_friend_request'),
  path('delete_friend_request/<str:sender_id>/<str:receiver_id>/', views.delete_frnd_req, name='delete_friend_request'),
  path('cancel_friend_request/<str:sender_id>/<str:receiver_id>/', views.cancel_frnd_req, name='cancel_friend_request'),
  path('accept_friend_request/<str:sender_id>/<str:receiver_id>/', views.accept_frnd_req, name='accept_friend_request'),

  path('friends/', views.view_friends, name='friends'),
  path('remove_from_friend_list/<str:friend_id>/', views.remove_from_friend_list, name='remove_from_friend_list'),

  path('notifications/', views.notifications, name='notifications'),

  path('start_or_join_chat/<str:profile_id>/', views.start_or_join_chat, name='start_or_join_chat'),
  path('inbox/<str:room_name>/', views.inbox, name='inbox'),
  path('messages/', views.messages, name='messages'),

]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
  path('create_post/', views.create_post, name='create_post'),
  path('edit_post/<str:pk>/', views.edit_post, name='edit_post'),
  path('delete_post/<str:pk>/', views.delete_post, name='delete_post'),
  path('confirm_delete/<str:pk>/', views.confirm_delete, name='confirm_delete'),
]

socialblog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import path,include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('post/', include('post.urls')),
    re_path('media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path('static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/models.py
from django.db import models
from account.models import Profile
import uuid
from django.utils import timezone
# Create your models here.

class Reply(models.Model):
  id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
  owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
  reply_content = models.TextField(max_length=200, null=True, blank=True)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)



class Comment(models.Model):
  id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
  owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
  comment_content = models.TextField(max_length=200, null=True, blank=True)
  reply = models.ForeignKey(Reply, on_delete=models.CASCADE, null=True, blank=True)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)


#new ui onojayi upvote and downvote bad, upvote r jaygay like

class Post(models.Model):
  id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
  owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
  post_content = models.TextField(max_length=2000, null=True, blank=True)
  post_img = models.ImageField(upload_to='uploaded_images', blank=True, null=True)
  upvote = models.IntegerField(null=True, blank=True)
  downvote = models.IntegerField(null=True, blank=True)
  comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)

  def __str__(self):
    return   self.post_content

post/forms.py
from django.forms import ModelForm
from .models import Post, Comment, Reply

class post_form(ModelForm):
  class Meta:
    model = Post
    fields = ['post_content', 'post_img']

  def __init__(self, *arg, **kwargs):
    super(post_form, self).__init__(*arg, **kwargs)

    self.fields['post_content'].widget.attrs['placeholder'] = 'Write your post content, max-length 2000 characters'

post/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages as django_messages
from account.models import Profile, Notifications
from .models import Post, Comment, Reply
from .forms import post_form
# Create your views here.


@login_required(login_url='account:login')
def create_post(request):
  form = post_form()
  profile = request.user.profile

  if request.method == 'POST':
    form = post_form(request.POST, request.FILES)
    if form.is_valid():
      p_form = form.save(commit=False)
      p_form.owner = profile
      p_form.save()
      django_messages.success(request, 'post created successfully')

      return redirect('account:profile', pk=profile.id)

  context = {
    'form' : form
  }
  return render(request, 'post/post_form.html', context)


@login_required(login_url='account:login')
def edit_post(request, pk):
  post = Post.objects.get(id=pk)
  form = post_form(instance=post)
  if request.method == 'POST':
    form = post_form(request.POST, request.FILES, instance=post)
    if form.is_valid():
      form.save()
      django_messages.success(request, 'post updated')
      return redirect('account:profile', pk=request.user.profile.id)

  context = {
    'form':form
  }
  return render(request, 'post/post_form.html', context)


@login_required(login_url='account:login')
def delete_post(request, pk):
  profile_id = request.user.profile.id
  post = Post.objects.get(id=pk)
  post_owner = post.owner.id

  if profile_id != post_owner :
    return redirect('account:index')

  context = {
    'post':post,
  }

  return render(request, 'post/delete_post.html', context)

@login_required(login_url='account:login')
def confirm_delete(request, pk):
  profile_id = request.user.profile.id
  post = Post.objects.get(id=pk)
  post_owner = post.owner.id

  if profile_id == post_owner:
    post.delete()
    django_messages.warning(request, 'post deleted')
    return redirect('account:profile', pk=profile_id)
  else:
    return redirect('account:index')

post/templates/post/delete_post.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Kenia&family=Mukta:wght@300;700&display=swap" rel="stylesheet">
  <title>Socialblog | stay connected</title>
</head>
<body>
  {% if messages %}
    {% for message in messages %}
      <div class="alert_box">
        <div class="alert-text" >
          <p>{{message}}</p>
        </div>
        <span id="alert-close-btn">
          <i class="fa-solid fa-xmark close_btn_icon"></i>
        </span>
      </div>
    {% endfor %}
  {% endif %}

  <main class="main_div">
    <div class="form_div">
  
      <div class="form_header">
        <div class="go_back_button">
          <a href="{% url 'account:profile' pk=request.user.profile.id %}">
            <i class="fa-solid fa-arrow-left" style="color: #abaeb3;"></i>
          </a>
        </div>
        <div class="form_header_text">
          <p>
            Are You Sure ? Deleted Post Is Not Recoverable
          </p>
        </div>
      </div>
  
      <div class="form_main_section">
        <div class="post">
  
          <div class="post_header post_const_margin">
            <div class="profile_picture post_profile_picture">
              <a><img src="{{post.owner.profile_picture.url}}" class="profile_picture_img" alt="profile_picture" ></a>
            </div>
            <div class="post_owner_div">
              <a>
                <p>{{post.owner.name}}</p>
                <small>{{post.created}}</small>
              </a>
            </div>
          </div>
      
          <div class="post_text_content post_const_margin">
            <p>
              {{post.post_content}}
            </p>
          </div>
      
          {% if post.post_img %}
            <div class="post_content">
              <img src="{{post.post_img.url}}" alt="uploaded_image" >
            </div>
          {% endif %}
  
          <div class="post_statics post_const_margin">
            <small><a>Gellert Grindelwald,rin walder and 52 others</a></small>
            <small>and</small>
            <small class="comment_static_small"><a>7 comments</a></small>
          </div>
      
          <div class="post_buttons post_const_margin">
            
            <a class="like_button_div">
              <button class="like_button">
                <i class="fa-regular fa-thumbs-up" style="color: #abaeb3;"></i>
              </button>
            </a>
            
            <a class="comment_button_div">
              <button class="comment_button">
                <i class="fa-regular fa-comment" style="color: #abaeb3;"></i>
              </button>
            </a>
          </div>
      
          <div class="post_comment_section post_const_margin">
      
            <p class="view_all_comments"><a>View more comments</a></p>
      
            <div class="commenter_box">
      
              <div class="comment_header">
                <div class="profile_picture cmnt_profile_picture">
                  <a>
                    <img src="images/profile_images/person-3.jpg" class="profile_picture_img" alt="profile_picture" >
                  </a>
                </div>
                <div class="comment_owner">
                  <a><p>rina walder</p></a>
                </div>
              </div>
      
              <div class="comment_content">
                <p>In response, Newt Scamander's former professor</p>
                <small class="commenter_box_small reply_box_btn">Reply</small>
                <small class="commenter_box_small">sep 6 </small>
              </div>
      
              <div class="input_box input_for_reply">
                <form class="input_box_form">
                  <input type="text" placeholder="write a reply">
                  <button>
                    <i class="fa-regular fa-paper-plane" style="color: #abaeb3;"></i>
                  </button>
                </form>
              </div>
      
            </div>
      
            <div class="comment_input_box">
              
              <div class="profile_picture cmnt_input_profile_picture">
                <a>
                  <img src="images/profile_images/person-3.jpg" class="profile_picture_img" alt="profile_picture" >
                </a>
              </div>
                
              <form class="input_box_form input_for_comment">
                <input type="text" placeholder="write your comment">
                <button>
                  <i class="fa-regular fa-paper-plane" style="color: #abaeb3;"></i>
                </button>
              </form>
            
            </div>
      
          </div>
        </div>
      </div>    
  
      <div class="form_button_section">
        <a href="{% url 'post:confirm_delete' pk=post.id %}" class="btn btn_form">Confirm Delete</a>
        <a href="{% url 'account:profile' pk=request.user.profile.id %}" class="btn btn_form">Go Back</a>
      </div>
  
    </div>
  </main>

  <script src="{% static 'js/index.js' %}" ></script>
</body>
</html>

post/templates/post/post_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Kenia&family=Mukta:wght@300;700&display=swap" rel="stylesheet">
  <title>Socialblog | stay connected</title>
</head>
<body>
  {% if messages %}
    {% for message in messages %}
      <div class="alert_box">
        <div class="alert-text" >
          <p>{{message}}</p>
        </div>
        <span id="alert-close-btn">
          <i class="fa-solid fa-xmark close_btn_icon"></i>
        </span>
      </div>
    {% endfor %}
  {% endif %}

  <main class="main_div">

    <div class="form_div">
  
      <div class="login_form_header">

        <a href="{% url 'account:profile' pk=request.user.profile.id %}"><p>Go Back To Profile</p></a>
      
        
      </div>
  
      <form method="POST" class="form" enctype="multipart/form-data">

        {% csrf_token %}

        {% for field in form %}

          <label>{{field.label}}:</label>
          {{field}}

          {{field.helptext}}

        {% endfor %}
  
        <button type="submit" class="btn btn_login">Submit</button>
  
      </form>
    
    </div>
    
  </main>
  <script src="{% static 'js/index.js' %}" ></script>
</body>
</html>