account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
  path('',views.index, name='index'),
  path('search-results/', views.search_result, name='search-result'),
  path('about/', views.about, name='about'),
  path('signup/', views.signup, name='signup'),
  path('login/', views.loginuser, name='login'),
  path('take_a_tour/', views.take_a_tour, name='take-a-tour'),
  path('logout/', views.logoutuser, name='logout'),

  path('profile/<str:pk>/', views.profile, name='profile'),
  path('profile_form/<str:pk>/', views.edit_profile, name='profile_form'),

  # path('search_profiles/<str:search_query>/', views.search_profiles, name='search_profiles'),
  path('search_profiles/', views.search_profiles, name='search_profiles'),

  path('send_friend_request/<str:sender_id>/<str:receiver_id>/', views.send_frnd_req, name='send_friend_request'),
  path('delete_friend_request/<str:sender_id>/<str:receiver_id>/', views.delete_frnd_req, name='delete_friend_request'),
  path('cancel_friend_request/<str:sender_id>/<str:receiver_id>/', views.cancel_frnd_req, name='cancel_friend_request'),
  path('accept_friend_request/<str:sender_id>/<str:receiver_id>/', views.accept_frnd_req, name='accept_friend_request'),

  path('friends/', views.view_friends, name='friends'),
  path('remove_from_friend_list/<str:friend_id>/', views.remove_from_friend_list, name='remove_from_friend_list'),

  path('notifications/', views.notifications, name='notifications'),

  path('start_or_join_chat/<str:profile_id>/', views.start_or_join_chat, name='start_or_join_chat'),
  path('inbox/<str:room_name>/', views.inbox, name='inbox'),
  path('messages/', views.messages, name='messages'),

]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
  path('create_post/', views.create_post, name='create_post'),
  path('edit_post/<str:pk>/', views.edit_post, name='edit_post'),
  path('delete_post/<str:pk>/', views.delete_post, name='delete_post'),
  path('confirm_delete/<str:pk>/', views.confirm_delete, name='confirm_delete'),
]

socialblog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import path,include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('post/', include('post.urls')),
    re_path('media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path('static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Kenia&family=Mukta:wght@300;700&display=swap" rel="stylesheet">
  <title>Socialblog | stay connected</title>
</head>
<body>
  
  <main class="main_div_about">
    <div class="main_section">

      <div class="main_picture">
        {% if admin.profile_picture %}
          <img src="{{admin.profile_picture.url}}" alt="yasir_webdev" >
        {% else %}
          <img src="media/profile_images/Yasir_webdev.jpg"  alt="yasir_webdev">
        {% endif %}
      </div>
      <div class="information">
        <p>This Is A Demo Website Made For Practice</p>
        <p>It's Incomplete, some functionality and UI still underdevlopment</p>
        <p>Completed functionality Listed Below</p>
        <p>Developed By <span><a href="{% url 'account:profile' pk=admin.id %}" class="link_bold" >Yasir_webdev</a></span></p>
        <P>This Website Has All The Functionality Listed Below</P>
        <div class="funtionality_div">
          <ul>
            <li><div class="list_dot"></div><p>Live Messaging</p></li>
            <li><div class="list_dot"></div><p>Searching Functionality</p></li>
            <li><div class="list_dot"></div><p>Making Friends</p></li>
            <li><div class="list_dot"></div><p>Making Posts and Sharing Them</p></li>
            <li><div class="list_dot"></div><p>Like and Comment(underdevlopment)</p></li>
            <li><div class="list_dot"></div><p>SignUp and Login/Authentication</p></li>
          </ul>
        </div>
        <p>It Utilizes These Technology</p>
        <ul>
          <li><div class="list_dot"></div><p>Django Channeles</p></li>
          <li><div class="list_dot"></div><p>Django, Python</p></li>
          <li><div class="list_dot"></div><p>Javascript</p></li>
          <li><div class="list_dot"></div><p>Html and Css</p></li>
        </ul>
        <p>Find Me Here</p>
        <ul>
          <li><div class="list_dot"></div><a href="">My Website</a></li>
          <li><div class="list_dot"></div><a href="">Twitter</a></li>
          <li><div class="list_dot"></div><a href="">Github</a></li>
          <li><div class="list_dot"></div><a href="">Facebook</a></li>
        </ul>
      </div>


    </div>
  </main>

  <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" media="all" type="text/css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Kenia&family=Mukta:wght@300;700&display=swap" rel="stylesheet">
  <script src="{% static 'js/index.js' %}" defer ></script>
  {% block title %}
    <title>SocialBlog</title>
  {% endblock title %}
</head>
<body>
  {% include 'navbar.html' %}

  {% if messages %}
    {% for message in messages %}
      <div class="alert_box">
        <div class="alert-text" >
          <p>{{message}}</p>
        </div>
        <span id="alert-close-btn">
          <i class="fa-solid fa-xmark close_btn_icon"></i>
        </span>
      </div>
    {% endfor %}
  {% endif %}

  {% include 'section_left.html' %}

  {% block content %}

  
  {% endblock content %}

</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Kenia&family=Mukta:wght@300;700&display=swap" rel="stylesheet">
  <title>Socialblog | stay connected</title>
</head>
<body>
  {% include 'navbar.html' %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert_box">
        <div class="alert-text" >
          <p>{{message}}</p>
        </div>
        <span id="alert-close-btn">
          <i class="fa-solid fa-xmark close_btn_icon"></i>
        </span>
      </div>
    {% endfor %}
  {% endif %}

  {% include 'section_left.html' %}
  
  <main class="section_middle">
    <div class="section_middle_inner_div">
      <div class="feed">
        {% for post in posts %}
          <div class="post">
    
            <div class="post_header post_const_margin">
              <div class="profile_picture post_profile_picture">
                <a href="{% url 'account:profile' pk=post.owner.id %}" >
                  <img src="{{post.owner.profile_picture.url}}" class="profile_picture_img" alt="post_picture" >
                </a>
              </div>
              <div class="post_owner_div">
                <a>
                  <p>{{post.owner.name}}</p>
                  <small>{{post.created}}</small>
                </a>
              </div>
            </div>
        
            <div class="post_text_content post_const_margin">
              <p>{{post.post_content}}</p>
            </div>
            {% if post.post_img %}
              <div class="post_content">
                <img src="{{post.post_img.url}}" alt="uploaded_image" >
              </div>
            {% endif %}
        
            <div class="post_statics post_const_margin">
              <small><a>Gellert Grindelwald,rin walder and 52 others</a></small>
              <small>and</small>
              <small class="comment_static_small"><a>7 comments</a></small>
            </div>
        
            <div class="post_buttons post_const_margin">
              
              <a class="like_button_div">
                <button class="like_button">
                  <i class="fa-regular fa-thumbs-up" style="color: #abaeb3;"></i>
                </button>
              </a>
              
              <a class="comment_button_div">
                <button class="comment_button">
                  <i class="fa-regular fa-comment" style="color: #abaeb3;"></i>
                </button>
              </a>
            </div>
        
            <div class="post_comment_section post_const_margin">
        
              <p class="view_all_comments"><a>View more comments</a></p>
        
              <div class="commenter_box">
        
                <div class="comment_header">
                  <div class="profile_picture cmnt_profile_picture">
                    <a>
                      <img src='images/profile_images/person-3.jpg' class="profile_picture_img" alt="profile_picture" >
                    </a>
                  </div>
                  <div class="comment_owner">
                    <a><p>rina walder</p></a>
                  </div>
                </div>
        
                <div class="comment_content">
                  <p>In response, Newt Scamander's former professor</p>
                  <small class="commenter_box_small reply_box_btn">Reply</small>
                  <small class="commenter_box_small">sep 6 </small>
                </div>
        
                <div class="input_box input_for_reply">
                  <form class="input_box_form">
                    <input type="text" placeholder="write a reply">
                    <button>
                      <i class="fa-regular fa-paper-plane" style="color: #abaeb3;"></i>
                    </button>
                  </form>
                </div>
        
              </div>
        
              <div class="comment_input_box">
                
                <div class="profile_picture cmnt_input_profile_picture">
                  <a>
                    <img src="images/profile_images/person-3.jpg" class="profile_picture_img" alt="profile_picture" >
                  </a>
                </div>
                  
                <form class="input_box_form input_for_comment">
                  <input type="text" placeholder="write your comment">
                  <button>
                    <i class="fa-regular fa-paper-plane" style="color: #abaeb3;"></i>
                  </button>
                </form>
              
              </div>
        
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </main>

  <section class="section_right">
    <div class="feature_post_div">
      <div class="feature_post_header">
        <p>Feature Posts</p>
      </div>
      <div class="carousel-container">
        <div class="carousel">
          <div class="carousel-slide">
            {% for post in first_two_posts %}
              {% if post.post_img %}
                <div class="carousel_slide_post_div cars_sd_post_one">
                  <div class="carousel_post_photo_div">
                    <img src="{{post.post_img.url}}" class="carousel_img" alt="post_picture">
                  </div>
                  <div class="carousel_post_info_div">
                    <p>Posted by <span><a href="{% url 'account:profile' pk=post.owner.id %}">{{post.owner.name}}</a></span></p>
                    <p>{{ post.post_content|slice:":100" }}</p>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
          <div class="carousel-slide">
            {% for post in second_two_posts %}
              {% if post.post_img %}
                <div class="carousel_slide_post_div cars_sd_post_one">
                  <div class="carousel_post_photo_div">
                    <img src="{{post.post_img.url}}" class="carousel_img" alt="post_picture">
                  </div>
                  <div class="carousel_post_info_div">
                    <p>Posted by <span><a href="{% url 'account:profile' pk=post.owner.id %}">{{post.owner.name}}</a></span></p>
                    <p>{{ post.post_content|slice:":100" }}</p>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
          <div class="carousel-slide">
            {% for post in third_two_posts %}
              {% if post.post_img %}
                <div class="carousel_slide_post_div cars_sd_post_one">
                  <div class="carousel_post_photo_div">
                    <img src="{{post.post_img.url}}" class="carousel_img" alt="post_picture">
                  </div>
                  <div class="carousel_post_info_div">
                    <p>Posted by <span><a href="{% url 'account:profile' pk=post.owner.id %}">{{post.owner.name}}</a></span></p>
                    <p>{{ post.post_content|slice:":100" }}</p>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
          <div class="carousel-slide">
            {% for post in fourth_two_posts %}
              {% if post.post_img %}
                <div class="carousel_slide_post_div cars_sd_post_one">
                  <div class="carousel_post_photo_div">
                    <img src="{{post.post_img.url}}" class="carousel_img" alt="post_picture">
                  </div>
                  <div class="carousel_post_info_div">
                    <p>Posted by <span><a href="{% url 'account:profile' pk=post.owner.id %}">{{post.owner.name}}</a></span></p>
                    <p>{{ post.post_content|slice:":100" }}</p>
                  </div>
                </div>
              {% endif %}
            {% endfor %}

          </div>
        </div>
      </div>
      <div class="feature_post_button_div">
        <button id="prev" class="btn btn_carousel btn_carousel_left"><i class="fa-solid fa-chevron-left" style="color: #abaeb3;"></i></button>
        <button id="next" class="btn btn_carousel btn_carousel_right"><i class="fa-solid fa-chevron-right" style="color: #abaeb3;"></i></button>
      </div>
    </div>

    <div class="contact_list_div">
      <div class="contact_div_header">
        <p>Contact List</p>
      </div>
      <div class="contact_list">
        {% for contact in contact_list %}
          <div class="contact">
            <div class="profile_picture contact_div_profile_img">
              <a href="{% url 'account:profile' pk=contact.id %}">
                <img src="{{contact.profile_picture.url}}" class="profile_picture_img" alt="profile_picture">
              </a>
            </div>
            <p><a href="{% url 'account:profile' pk=contact.id %}">{{contact.name}}</a></p>
          </div>
        {% empty %}
          <div class="contact">
            <div class="profile_picture contact_div_profile_img">
              <a href="#">
                <img src="images/profile_images/user-default.jpg" class="profile_picture_img" alt="profile_picture">
              </a>
            </div>
            <p><a>Friend List Will Be Here</a></p>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

templates/list_item.html
{% extends 'base.html' %}

{% block content %}

  <main class="main_div_right">

    <div class="multiple_type_list">

      <div class="typelist_div_two">
        <div class="typelist_button_div">
          <a href="{% url 'account:search_profiles'%}" class="btn btn_typelist">Search Profiles</a>
        </div>
      </div>

    </div>    
  
    {% for post in posts %}
      <div class="post">

        <div class="post_header post_const_margin">
          <div class="profile_picture post_profile_picture">
            <a href="{% url 'account:profile' pk=post.owner.id %}" >
              <img src="{{post.owner.profile_picture.url}}" class="profile_picture_img" alt="profile_picture" >
            </a>
          </div>
          <div class="post_owner_div">
            <a>
              <p>{{post.owner.name}}</p>
              <small>{{post.created}}</small>
            </a>
          </div>
        </div>
    
        <div class="post_text_content post_const_margin">
          <p>{{post.post_content}}</p>
        </div>
        {% if post.post_img %}
          <div class="post_content">
            <img src="{{post.post_img.url}}" alt="uploaded_image" >
          </div>
        {% endif %}
    
        <div class="post_statics post_const_margin">
          <small><a>Gellert Grindelwald,rin walder and 52 others</a></small>
          <small>and</small>
          <small class="comment_static_small"><a>7 comments</a></small>
        </div>
    
        <div class="post_buttons post_const_margin">
          
          <a class="like_button_div">
            <button class="like_button">
              <i class="fa-regular fa-thumbs-up" style="color: #abaeb3;"></i>
            </button>
          </a>
          
          <a class="comment_button_div">
            <button class="comment_button">
              <i class="fa-regular fa-comment" style="color: #abaeb3;"></i>
            </button>
          </a>
        </div>
    
        <div class="post_comment_section post_const_margin">
    
          <p class="view_all_comments"><a>View more comments</a></p>
    
          <div class="commenter_box">
    
            <div class="comment_header">
              <div class="profile_picture cmnt_profile_picture">
                <a>
                  <img src="images/profile_images/person-3.jpg" class="profile_picture_img" alt="profile_picture" >
                </a>
              </div>
              <div class="comment_owner">
                <a><p>rina walder</p></a>
              </div>
            </div>
    
            <div class="comment_content">
              <p>In response, Newt Scamander's former professor</p>
              <small class="commenter_box_small reply_box_btn">Reply</small>
              <small class="commenter_box_small">sep 6 </small>
            </div>
    
            <div class="input_box input_for_reply">
              <form class="input_box_form">
                <input type="text" placeholder="write a reply">
                <button>
                  <i class="fa-regular fa-paper-plane" style="color: #abaeb3;"></i>
                </button>
              </form>
            </div>
    
          </div>
    
          <div class="comment_input_box">
            
            <div class="profile_picture cmnt_input_profile_picture">
              <a>
                <img src="images/profile_images/person-3.jpg" class="profile_picture_img" alt="profile_picture" >
              </a>
            </div>
              
            <form class="input_box_form input_for_comment">
              <input type="text" placeholder="write your comment">
              <button>
                <i class="fa-regular fa-paper-plane" style="color: #abaeb3;"></i>
              </button>
            </form>
          
          </div>
    
        </div>
      </div>
    {% endfor %}

  </main>

{% endblock content %}

templates/navbar.html
<header>
  <div class="logo"><span><a href="{% url 'account:index' %}"><h1>Socialblog</h1></a></span></div>

  <form method="GET" action="{% url 'account:search-result' %}" class="search-bar">
    <input type="text" name="search_query" value="{{search_query}}" placeholder="what are u looking for" >
    <button type="submit">
      <i class="fa-solid fa-magnifying-glass"></i>
    </button>
  </form>

  <div class="nav_toogle_btn">
    <i class="fas fa-bars close_btn_icon" id="hamburger"></i>
    <i class="fa-solid fa-xmark close_btn_icon" id="cross_sign"></i>
  </div>

  <nav class="navigation">

    <ul class="nav_ul">
      <li><a href="{% url 'account:index' %}">Home</a></li>
      <li><a href="{% url 'account:friends' %}">Friends</a></li>
      <li><a href="{% url 'account:about' %}">About</a></li>
      {% if request.user.is_authenticated %}
        <li><a href="{% url 'account:logout' %}">Logout</a></li>
      {% else %}
        <li><a href="{% url 'account:login' %}">Login/SignUp</a></li>
        <li><a href="{% url 'account:take-a-tour' %}">Take A Tour</a></li>
      {% endif %}
      <li class="search_btn_holder"><a href="#" id="nav_search_btn">Search</a></li>
      <li class="nav_search_bar">
        <form method="GET" action="{% url 'account:search-result' %}" class="nav_search_bar_form">
          <input type="text" name="search_query" value="{{search_query}}" placeholder="Search" >
          <button type="submit" >
            <i class="fa-solid fa-magnifying-glass"></i>
          </button>
        </form>
      </li>
    </ul>
    <div class="profile_picture nav_profile_picture">
      {% if request.user.is_authenticated %}
        <a href="{% url 'account:profile' pk=request.user.profile.id %}">
          <img src="{{request.user.profile.profile_picture.url}}" class="profile_picture_img" alt="profile_picture">
        </a>
      {% else %}
        <a href="{% url 'account:login' %}">
          <img src="media/profile_images/user-default.jpg" class="profile_picture_img" alt="profile_picture">
        </a>
      {% endif %}
    </div>

  </nav>

</header>

templates/section_left.html
<section class="section_left" >
  <div class="section_left_inner_div">

    <div class="section_left_navigation">
    
      <div class="section_left_nav_profile_div">
        <div class="profile_picture left_nav_profile_img_div">
          {% if request.user.is_authenticated %}
            <a href="{% url 'account:profile' pk=request.user.profile.id %}">
              <img src="{{request.user.profile.profile_picture.url}}" class="profile_picture_img" alt="profile_picture">
            </a>
          {% else %}
            <a href="{% url 'account:login' %}">
              <img src="media/profile_images/user-default.jpg" class="profile_picture_img" alt="profile_picture">
            </a>
          {% endif %}
        </div>
        <div class="left_nav_profile_name">
          {% if request.user.is_authenticated %}
            <a href="{% url 'account:profile' pk=request.user.profile.id %}">
              {% if request.user.profile.name %}
                <p>{{request.user.profile.name}}</p>
              {% else %}
                <p>{{request.user.profile.username}}</p>
              {% endif %}
            </a>
          {% else %}
            <a href="{% url 'account:login' %}">
              <p>UserName</p>
            </a>
          {% endif %}
        </div>
      </div>  
      
      <div class="section_left_nav_navlist">
        {% if request.user.is_authenticated %}
          <a href="{% url 'account:profile' pk=request.user.profile.id %}"><i class="fa-regular fa-user" style="color: #abaeb3;"></i><span>Profile</span></a>
        {% else %}
          <a href="{% url 'account:login' %}"><i class="fa-regular fa-user" style="color: #abaeb3;"></i><span>Profile</span></a>
        {% endif %}
        <a href="{% url 'post:create_post' %}"><i class="fa-regular fa-square-plus" style="color: #abaeb3;"></i><span>New Post</span></a>
        <a href="{% url 'account:notifications' %}"><i class="fa-regular fa-bell" style="color: #abaeb3;"></i><span>Notifications</span></a>
        <a href="{% url 'account:messages' %}"><i class="fa-regular fa-message" style="color: #abaeb3;"></i><span>Messages</span></a>
        <a href="{% url 'account:about' %}"><i class="fa-solid fa-users-rectangle" style="color: #abaeb3;"></i><span>Groups</span></a>
      </div>
      
    </div>
    <div class="section_left_footer">
      <p>Demo Website For Practice</p>
      <p>
        &copy; 2023 <a href="#">Yasir_webdev</a>. All rights reserved.
      </p>
    </div>
  </div>

</section>